// src/components/test.component.ts
import { html } from "lit";
import { customElement, property } from "lit/decorators.js";
import { TailwindElement } from "../shared/tailwind.element";

@customElement("test-component")
export class TestComponent extends TailwindElement() {
	@property()
	name?: string = "World";

	render() {
		return html`
			<p>Hello, <b>${this.name}</b>!</p>
			<button
				class="bg-orange-200 text-green-200 p-2 rounded-full text-2xl"
			>
				Hello world!
			</button>
		`;
	}
}

// src/components/TestComponent.svelte
<script>
    import '@/src/tailwind.css';
    export let name = 'World'; 
    export let restProps = {};
</script>

<div {...restProps}>
    <p class="text-lg font-bold">Hello, <b>{name}</b>!</p>
    <button
        class="p-2 text-2xl text-green-200 bg-orange-200 rounded-full dark:text-white"
    >
        Hello world!
    </button>
</div>
